name: starwars_devconf
description: Flutter demo project using the swapi.dev as API
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core Architectural packages
  get_it: ^7.2.0 # Dependency injection
  injectable: ^1.5.3 # Dependency injection annotation
  flutter_bloc: ^8.0.1 # Bloc library
  equatable: ^2.0.3 # Equatable used for easy overriding equality

  # Serialization
  json_annotation: ^4.5.0 # json

  # Http
  dio: ^4.0.6
  dio_cache_interceptor: ^3.2.7
  dio_cache_interceptor_hive_store: ^3.1.1
  path_provider: ^2.0.10

  # Localization
  intl: ^0.17.0

  # Framework tweaks
  flutter_displaymode: ^0.4.0

  # UI
  cached_network_image: ^3.2.1
  animations: ^2.0.3 # animations
  sliver_tools: ^0.2.6 # Additional Sliver tools, used in product detail screen


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11 # Build runner for code generation

  # Json serializable
  json_serializable: ^6.2.0 # Used to generate json (de)serializer code
  injectable_generator: ^1.5.3 # Used to generate DI boilerplate

  # Linting
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
