name: starwars_devconf
description: Flutter demo project using the swapi.dev as API
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core Architectural packages
  get_it: ^7.2.0 # Dependency injection
  injectable: ^2.1.0 # Dependency injection annotation
  flutter_bloc: ^8.1.2 # Bloc library
  equatable: ^2.0.3 # Equatable used for easy overriding equality

  # Serialization
  json_annotation: ^4.8.0 # json

  # Http
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.1
  dio_cache_interceptor_hive_store: ^3.2.0
  path_provider: ^2.0.12

  # Localization
  intl: ^0.17.0

  # UI
  cached_network_image: ^3.2.3
  animations: ^2.0.7 # animations
  sliver_tools: ^0.2.9 # Additional Sliver tools, used in product detail screen


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3 # Build runner for code generation

  # Json serializable
  json_serializable: ^6.6.1 # Used to generate json (de)serializer code
  injectable_generator: ^2.1.4 # Used to generate DI boilerplate

  # Linting
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
